const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

const REPORTS_DIR = path.join(__dirname, '../../reports');

function ensureReportsDir() {
  if (!fs.existsSync(REPORTS_DIR)) {
    fs.mkdirSync(REPORTS_DIR, { recursive: true });
  }
}

function generatePDF(reportData, filename) {
  ensureReportsDir();
  const filePath = path.join(REPORTS_DIR, filename);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);

    doc.fontSize(22).fillColor('#00ff88').text('AI-Powered SOC Platform', { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(14).fillColor('#333').text('Threat Detection & Incident Response Report', { align: 'center' });
    doc.moveDown(1);
    doc.strokeColor('#00ff88').lineWidth(2).moveTo(50, doc.y).lineTo(545, doc.y).stroke();
    doc.moveDown(1);

    doc.fontSize(16).fillColor('#111').text(reportData.title);
    doc.moveDown(0.5);
    doc.fontSize(10).fillColor('#666');
    doc.text(`Report Type: ${reportData.type}`);
    doc.text(`Generated: ${new Date().toLocaleString()}`);
    doc.text(`Generated By: ${reportData.generatedBy || 'SOC Analyst'}`);
    if (reportData.dateRange) {
      doc.text(`Period: ${reportData.dateRange.start} - ${reportData.dateRange.end}`);
    }
    doc.moveDown(1);

    if (reportData.summary) {
      doc.fontSize(12).fillColor('#111').text('Executive Summary', { underline: true });
      doc.moveDown(0.3);
      doc.fontSize(10).fillColor('#333').text(reportData.summary, { align: 'justify' });
      doc.moveDown(1);
    }

    if (reportData.content?.statistics) {
      doc.fontSize(12).fillColor('#111').text('Statistics', { underline: true });
      doc.moveDown(0.3);
      const stats = reportData.content.statistics;
      Object.entries(stats).forEach(([key, value]) => {
        doc.fontSize(10).fillColor('#333').text(`${key}: ${value}`);
      });
      doc.moveDown(1);
    }

    if (reportData.content?.alerts?.length) {
      doc.fontSize(12).fillColor('#111').text('Security Alerts', { underline: true });
      doc.moveDown(0.3);
      reportData.content.alerts.slice(0, 20).forEach((alert, i) => {
        doc.fontSize(10).fillColor('#333').text(
          `${i + 1}. [${alert.severity?.toUpperCase()}] ${alert.title} - ${alert.sourceIp || 'N/A'}`
        );
      });
      doc.moveDown(1);
    }

    if (reportData.content?.incidents?.length) {
      doc.fontSize(12).fillColor('#111').text('Incidents', { underline: true });
      doc.moveDown(0.3);
      reportData.content.incidents.forEach((inc, i) => {
        doc.fontSize(10).fillColor('#333').text(
          `${i + 1}. ${inc.incidentId} - ${inc.title} [${inc.severity}/${inc.status}]`
        );
      });
      doc.moveDown(1);
    }

    if (reportData.content?.mitreMapping?.length) {
      doc.fontSize(12).fillColor('#111').text('MITRE ATT&CK Mapping', { underline: true });
      doc.moveDown(0.3);
      reportData.content.mitreMapping.forEach((m) => {
        doc.fontSize(10).fillColor('#333').text(`${m.techniqueId} - ${m.tactic}: ${m.technique}`);
      });
      doc.moveDown(1);
    }

    doc.moveDown(2);
    doc.fontSize(8).fillColor('#999').text(
      'NA-042026 – Group A | AI-Powered SOC Platform for Threat Detection and Incident Response',
      { align: 'center' }
    );
    doc.text('Confidential - For Internal Security Operations Use Only', { align: 'center' });

    doc.end();
    stream.on('finish', () => resolve(filePath));
    stream.on('error', reject);
  });
}

async function generateIncidentReport(incident, alerts, user) {
  const filename = `incident-${incident.incidentId}-${Date.now()}.pdf`;
  const reportData = {
    title: `Incident Report: ${incident.incidentId}`,
    type: 'incident',
    generatedBy: user?.name || 'SOC Analyst',
    summary: incident.aiSummary || incident.description,
    content: {
      statistics: {
        'Incident ID': incident.incidentId,
        Severity: incident.severity,
        Status: incident.status,
        'Related Alerts': alerts?.length || 0,
        'Source IPs': incident.sourceIps?.join(', ') || 'N/A',
      },
      alerts: alerts?.map((a) => ({
        title: a.title,
        severity: a.severity,
        sourceIp: a.sourceIp,
      })),
      mitreMapping: incident.mitreTechniques?.map((t, i) => ({
        techniqueId: incident.mitreTactics?.[i] || 'T0000',
        tactic: incident.mitreTactics?.[i] || 'Unknown',
        technique: t,
      })),
    },
  };

  const filePath = await generatePDF(reportData, filename);
  return { filename, filePath, reportData };
}

async function generateThreatReport(alerts, stats, user) {
  const filename = `threat-analysis-${Date.now()}.pdf`;
  const reportData = {
    title: 'Threat Analysis Report',
    type: 'threat_analysis',
    generatedBy: user?.name || 'SOC Analyst',
    dateRange: stats.dateRange,
    summary: `Analysis of ${alerts.length} security alerts. Critical: ${stats.critical || 0}, High: ${stats.high || 0}, Medium: ${stats.medium || 0}, Low: ${stats.low || 0}.`,
    content: {
      statistics: stats,
      alerts,
      mitreMapping: alerts.map((a) => ({
        techniqueId: a.mitreTechniqueId,
        tactic: a.mitreTactic,
        technique: a.mitreTechnique,
      })),
    },
  };

  const filePath = await generatePDF(reportData, filename);
  return { filename, filePath, reportData };
}

async function generateLogSummaryReport(logs, user) {
  const filename = `log-summary-${Date.now()}.pdf`;
  const suspicious = logs.filter((l) => l.isSuspicious).length;
  const reportData = {
    title: 'Log Summary Report',
    type: 'log_summary',
    generatedBy: user?.name || 'SOC Analyst',
    summary: `Processed ${logs.length} log entries. ${suspicious} flagged as suspicious.`,
    content: {
      statistics: {
        'Total Logs': logs.length,
        Suspicious: suspicious,
        'Auth Logs': logs.filter((l) => l.logType === 'auth').length,
        'Apache Logs': logs.filter((l) => l.logType === 'apache').length,
      },
    },
  };

  const filePath = await generatePDF(reportData, filename);
  return { filename, filePath, reportData };
}

module.exports = {
  generatePDF,
  generateIncidentReport,
  generateThreatReport,
  generateLogSummaryReport,
};
