import { useState, useEffect } from 'react';
import { FileText, Download, RefreshCw } from 'lucide-react';
import { reportsAPI } from '../services/api';
import LoadingSpinner from '../components/common/LoadingSpinner';
import { formatDate } from '../utils/helpers';

export default function Reports() {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState('');

  useEffect(() => { loadReports(); }, []);

  const loadReports = async () => {
    setLoading(true);
    try {
      const { data } = await reportsAPI.getAll();
      setReports(data.data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const generateReport = async (type) => {
    setGenerating(type);
    try {
      if (type === 'threat') await reportsAPI.generateThreat();
      else if (type === 'logs') await reportsAPI.generateLogSummary();
      loadReports();
    } catch (err) {
      alert(err.response?.data?.message || 'Report generation failed');
    } finally {
      setGenerating('');
    }
  };

  const downloadReport = async (filename) => {
    try {
      const { data } = await reportsAPI.download(filename);
      const url = window.URL.createObjectURL(new Blob([data]));
      const link = document.createElement('a');
      link.href = url;
      link.download = filename;
      link.click();
      window.URL.revokeObjectURL(url);
    } catch (err) {
      alert('Download failed');
    }
  };

  const typeLabels = { incident: 'Incident Report', threat_analysis: 'Threat Analysis', log_summary: 'Log Summary' };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-display font-bold flex items-center gap-2">
          <FileText className="text-soc-accent2" /> Reports
        </h1>
        <p className="text-soc-muted text-sm mt-1">Generate and download security analysis reports</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {[
          { type: 'threat', label: 'Threat Analysis Report', desc: 'Comprehensive alert & MITRE analysis' },
          { type: 'logs', label: 'Log Summary Report', desc: 'Overview of processed log entries' },
        ].map((r) => (
          <div key={r.type} className="glass-card-hover p-5">
            <h3 className="font-semibold">{r.label}</h3>
            <p className="text-xs text-soc-muted mt-1 mb-4">{r.desc}</p>
            <button
              onClick={() => generateReport(r.type)}
              disabled={generating === r.type}
              className="btn-primary text-sm flex items-center gap-2 w-full justify-center"
            >
              {generating === r.type ? <RefreshCw size={14} className="animate-spin" /> : <FileText size={14} />}
              {generating === r.type ? 'Generating...' : 'Generate PDF'}
            </button>
          </div>
        ))}
      </div>

      <div className="glass-card overflow-hidden">
        <div className="p-4 border-b border-white/10">
          <h2 className="font-semibold">Report History</h2>
        </div>
        {loading ? <LoadingSpinner /> : (
          <table className="w-full text-sm">
            <thead>
              <tr className="text-soc-muted text-xs border-b border-white/10 bg-white/5">
                <th className="text-left p-3">Title</th>
                <th className="text-left p-3">Type</th>
                <th className="text-left p-3">Generated By</th>
                <th className="text-left p-3">Date</th>
                <th className="p-3">Action</th>
              </tr>
            </thead>
            <tbody>
              {reports.length === 0 ? (
                <tr><td colSpan={5} className="p-8 text-center text-soc-muted">No reports generated yet</td></tr>
              ) : reports.map((r) => (
                <tr key={r._id} className="border-b border-white/5 table-row-hover">
                  <td className="p-3">{r.title}</td>
                  <td className="p-3"><span className="text-xs px-2 py-0.5 rounded bg-white/10">{typeLabels[r.type]}</span></td>
                  <td className="p-3 text-soc-muted">{r.generatedBy?.name || 'System'}</td>
                  <td className="p-3 font-mono text-xs">{formatDate(r.createdAt)}</td>
                  <td className="p-3">
                    {r.filePath && (
                      <button onClick={() => downloadReport(r.filePath)} className="btn-primary text-xs flex items-center gap-1">
                        <Download size={12} /> PDF
                      </button>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  );
}
